SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `TBL_DATABASE_CONNECTION` CASCADE;

DROP TABLE IF EXISTS `TBL_IMPORT_FAILURE` CASCADE;

CREATE TABLE `TBL_DATABASE_CONNECTION`(
 `ID` VARCHAR(32) NOT NULL COMMENT '逻辑主键',
 `URL` VARCHAR(100)   COMMENT '数据库连接url',
 `USERNAME` VARCHAR(50) COMMENT '数据库用户',
 `PASSWORD` VARCHAR(50)  COMMENT '连接密码',
 `SYSTEM_FROM` VARCHAR(32) COMMENT '表所属的系统',
 `STATUS` TINYINT DEFAULT 0 COMMENT '状态标记',

 	CONSTRAINT `PK_TBL_DATABASE_CONNECTION` PRIMARY KEY (`ID`),
 	CONSTRAINT `UQ_TBL_DATABASE_CONNECTION` UNIQUE (`URL`)
) COMMENT '数据库连接状态表';

CREATE TABLE `TBL_IMPORT_FAILURE`(
 `ID` VARCHAR(32) NOT NULL COMMENT '逻辑主键',
 `CHECK_TIME` VARCHAR(32)   COMMENT '检测到的时间',
 `TASK_NAME` VARCHAR(100) COMMENT '任务名称',
 `BG_TABLE_NAME` VARCHAR(100)  COMMENT '任务对应的表',

 	CONSTRAINT `PK_TBL_IMPORT_FAILURE` PRIMARY KEY (`ID`)
) COMMENT 'sqoop导入数据失败详情';

SET FOREIGN_KEY_CHECKS=1;