SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `TBL_INTERFACE_CONNECTION` CASCADE;

CREATE TABLE `TBL_INTERFACE_CONNECTION`(
 `ID` VARCHAR(32) NOT NULL COMMENT '逻辑主键',
 `URL` VARCHAR(100)   COMMENT '连接url',
 `SYSTEM_FROM` VARCHAR(32) COMMENT '接口所属的系统',
 `STATUS` TINYINT COMMENT '连接状态',
 	CONSTRAINT `PK_TBL_INTERFACE_CONNECTION` PRIMARY KEY (`ID`),
 	CONSTRAINT `UQ_TBL_INTERFACE_CONNECTION` UNIQUE (`URL`)
) COMMENT '接口连接状态表';

SET FOREIGN_KEY_CHECKS=1;